---
abstract: 'Create number continuations'
author:
  - 'Steven Schubiger <schubiger@cpan.org>'
build_requires:
  Test::More: '0'
configure_requires:
  Module::Build: '0.42'
dynamic_config: 1
generated_by: 'Module::Build version 0.421, CPAN::Meta::Converter version 2.142690'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Number-Continuation
provides:
  Number::Continuation:
    file: lib/Number/Continuation.pm
    version: 0.04_01
requires:
  Carp: '0'
  Exporter: '0'
  Params::Validate: '0'
  boolean: '0'
resources:
  license: http://dev.perl.org/licenses/
version: 0.04_01
